### ISSUE TITLE
Implement `inverse_transform` for `@pipeline` models where this makes sense

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJBase.jl#384]
Context: https://github.com/alan-turing-institute/MLJ.jl/issues/625

Probably not a high priority as you can always roll your own using a learning network (as I explain at linked issue)

**Comment by ablaom** [comment]
cc @Leonardbcm

**Comment by Leonardbcm** [comment]
Thanks for adding this. It is indeed not necessary since you can always construct a learning model, 
It just seems more consistent to be able to reverse a series of unsupervised transformations. Morevover, it is conceptualy strange to be able to call `transform` on a pipeline and not be able to inverse it.

**Comment by ablaom** [comment]
I expect this issue will be addressed simultaneously with https://github.com/alan-turing-institute/MLJ.jl/issues/594
