### ISSUE TITLE
Precompilation workload

### ISSUE THREAD

**Issue by olivierlabayle** [JuliaAI/MLJBase.jl#924]
Hi,

I am trying to add a precompilation workload to my package but it fails due to MLJBase with the following error: 

```LoadError: Evaluation into the closed module `MLJBase` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `MLJBase` with `eval` during precompilation - don't do this.```

The triggering piece of code seems to be the following pipeline definition:

```julia
with_encoder(model; encoder=encoder()) = Pipeline(TreatmentTransformer(;encoder=encoder),  model)
```

I've seen there has been a [tentative](https://github.com/JuliaAI/MLJBase.jl/pull/900) to add a workload in the past, but this aborted. Should I just give up on that at the moment?

**Comment by ablaom** [comment]
Mmm. I honestly don't know where `eval` would come in the `Pipeline` model code. But possibly this is a red herring and the real issue is the one pointed out it in the failed attempt. The remedy (get rid of the `INTERFACE_MODE` global constant) is not something likely in the near future. 

Sorry I cannot be more helpful.

**Comment by olivierlabayle** [comment]
I see, thank you, I think that answers this issue for now!
